application: srm-results
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: usage.py

- url: /xml
  script: test.py

libraries:
- name: webapp2
  version: latest